### ISSUE TITLE
Is it available for Linux?

### ISSUE THREAD

**Issue by 6km** [My-Quran-Tajwid/quran_publisher_desktop#1] opened 2024-12-19 00:10 UTC
Assalamu'alaikum!

I'm a Linux user. I'd like to test the app on linux but i can't find a build for linux?
Can you automate the build process and upload Windows, MacOS and Linux executables on the releases tab for each version? It will be easier for new users to come and test the app!

I'm exited to try it! Jazakallahu Khairan!

**Comment by iqfareez** [comment] 2024-12-19 00:15
Waalaikumsalam Wbt.

Thank you for your interest in this project.

Sure, I'll be uploading the binaries after sorting few things out. Stay tuned!










________________________________
From: Mohammed Taha ***@***.***>
Sent: Thursday, 19 December, 2024 08:10
To: My-Quran-Tajwid/quran_publisher_desktop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [My-Quran-Tajwid/quran_publisher_desktop] Is it available for Linux? (Issue #1)


Assalamu'alaikum!

I'm a Linux user. I'd like to test the app on linux but i can't find a build for linux?
Can you automate the build process and upload Windows, MacOS and Linux executables on the releases tab?

I'm exited to try it! Jazakallahu Khairan!

**Comment by 6km** [comment] 2024-12-19 01:47
@iqfareez Thank you so much brother! Subhan'allah I had been trying to run Mushaf Publication of KFGQPC on Linux; it's not officially supported on linux, and Allah guided me to find your new application.

**Comment by shaaanuu** [comment] 2024-12-20 13:51
I can help with the linux, windows and android automated build...
ios and macos require additional steps to sign the build. So i dont think its worth it (maybe i am wrong).

**Comment by iqfareez** [comment] 2024-12-20 14:18
@shaaanuu You're welcome to contribute 😊. 

For now I think let's focus on desktop first ie Windows, MacOS, Linux.

**Comment by shaaanuu** [comment] 2024-12-20 14:50
#3  done. Only linux and windows for now.

**Comment by iqfareez** [comment] 2024-12-20 15:16
![image](https://github.com/user-attachments/assets/92ce2386-06a0-4b7d-813e-30de653058ba)

Running the app on Ubuntu (WSL on Windows 11). Works great so far.

**Comment by shaaanuu** [comment] 2024-12-20 15:26
![Screenshot_2024-12-20-20-48-46_1366x768](https://github.com/user-attachments/assets/98d28402-7515-4624-87a2-892786576589)

hmmm....Something is wrong with me though. The font...
But Alhamdulillah it's work on ubuntu, right? I will check what's the causing problem on arch

**Comment by shaaanuu** [comment] 2024-12-20 15:29
well, look into the pull request #3 and if you are satisfied with it, you can merge it and close this issue.

**Comment by iqfareez** [comment] 2024-12-20 15:41
> hmmm....Something is wrong with me though. The font... But Alhamdulillah it's work on ubuntu, right? I will check what's the causing problem on arch

I suspect it might be missing font issue. By default, it will depend on installed system font. On windows, the [app from KFGQPC](https://nashr.qurancomplex.gov.sa/) will install the required fonts on setup.

![image](https://github.com/user-attachments/assets/aebb73d2-088f-4ce3-b5ae-336a09caad9c)

@shaaanuu Please try checkout this branch https://github.com/My-Quran-Tajwid/quran_publisher_desktop/commit/6a427def7714831b523e7a72e6a682ccfacd2429 and run it. I've added functionality so that it will load from assets instead of from system.

**Comment by shaaanuu** [comment] 2024-12-20 15:45
Oh. I will check it tomorrow. Inshallah

**Comment by 6km** [comment] 2024-12-20 15:54
@iqfareez @shaaanuu Thanks for your effort brothers! May Allah reward you with good!
I'm excited to try the Linux binary on Debian!

**Comment by shaaanuu** [comment] 2024-12-21 16:01
@iqfareez Yep the bb33e19 works perfectly fine on arch now. So in that case i think the issue is closed...

**Comment by iqfareez** [comment] 2024-12-21 16:02
@shaaanuu Alhamdulillah. Thanks for the confirmation!

**Comment by 6km** [comment] 2024-12-21 21:41
@iqfareez @shaaanuu I downloaded the portable version of Linux and it works but the fonts issue isn't fixed in that build. By the way, I use Debian 12.

Can you [make a release](https://github.com/My-Quran-Tajwid/quran_publisher_desktop/releases) so the new version gets published with the fix?

Thanks for your effort, brothers!

![image](https://github.com/user-attachments/assets/19a5d800-403a-4683-9c9a-3f475c9a0790)

**Comment by shaaanuu** [comment] 2024-12-22 04:17
That's the old build. New build will be released by @iqfareez

**Comment by iqfareez** [comment] 2024-12-23 01:27
Alhamdulillah. I've published the first preview release here: https://github.com/My-Quran-Tajwid/quran_publisher_desktop/releases/tag/0.0.1%2B1

![Screenshot from 2024-12-23 09-15-18](https://github.com/user-attachments/assets/9717cc0a-afca-46d8-b5b0-c4cda0d88a19)

For now, it's available for Windows & Linux. Inshallah, I'll try to expand to MacOS soon.

Steps:
- Download linux-x64.zip from the assets
- Unzip
- Run `quran_publisher_dekstop`

![image](https://github.com/user-attachments/assets/fdf6547d-bf48-45a2-9589-f96865ae5699)


For Linux, please let me know if we should try to package the app as rpm/deb/AppImage etc. Thank you for those who helped😊.Closing this issue.

**Closed as completed by iqfareez** 2024-12-23 01:27 UTC
Labels: good first issue

**Comment by 6km** [comment] 2024-12-23 14:12
Alhamdulillah. I think it would be very good to have .rpm and .deb builds for Linux.

**Comment by 6km** [comment] 2024-12-23 14:13
@iqfareez Alhamdulillah. I think it would be very good to have .rpm and .deb builds for Linux.
